version: "3"
services:
  web-app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    container_name: web-app-container
    ports:
      - "5001:5000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-container
    ports:
      - "5002:5002"