services:
  web-app:
    build:
      context: ./web_app
      dockerfile: Dockerfile
    image: awesomeadi00/webapp:latest
    container_name: personaverse-webapp-container
    ports:
      - "5001:5000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: awesomeadi00/client:latest
    container_name: personaverse-client-container
    ports:
      - "5002:5002"
  database:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: